# Generated by Django 3.1.2 on 2020-10-27 20:30

import ckeditor.fields
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Img', models.ImageField(blank=True, null=True, upload_to='contactPics')),
                ('Message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=250)),
                ('Slug', models.SlugField(unique=True)),
                ('Prix1', models.CharField(max_length=100)),
                ('Prix2', models.CharField(max_length=100)),
                ('Category', multiselectfield.db.fields.MultiSelectField(choices=[('PLAYSTATION', 'PLAYSTATION'), ('NINTENDO', 'NINTENDO'), ('XBOX', 'XBOX')], max_length=25)),
                ('Description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('Img', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
