# Generated by Django 3.1.2 on 2020-10-29 11:52

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vghApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('PLAYSTATION', 'PLAYSTATION'), ('NINTENDO', 'NINTENDO'), ('XBOX', 'XBOX'), ('FIGURINE', 'FIGURINE')], max_length=34),
        ),
    ]
