# Generated by Django 3.1.2 on 2020-10-29 16:35

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vghApp', '0002_auto_20201029_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('PLAYSTATION', 'PLAYSTATION'), ('NINTENDO', 'NINTENDO'), ('XBOX', 'XBOX'), ('FIGURINE', 'FIGURINE'), ('EXPOSITION', 'EXPOSITION'), ('ENCHER', 'ENCHER')], max_length=52),
        ),
    ]
