# Generated by Django 3.1.2 on 2020-11-01 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vghApp', '0006_news_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Img1',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='product',
            name='Img2',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='product',
            name='Img3',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
    ]
